version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .    
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: /code/entry_point.sh
  worker:
    build: .
    links:
      - redis
    command: python appherokureg/worker.py
    volumes:
      - .:/code
    depends_on:
      - redis